# Generated by Django 3.0.2 on 2020-02-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_sensor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
    ]
